BuildLayer(
		'h',
		'',
		'',
		'',
		'250',
		'250',
		'',
		'',
		'',
		'2',
		'5',
		'1px Solid #999999',
		'1px Solid #999999',
		'1px Solid #999999',
		'1px Solid #999999',
		'center',
		'transparent',
		'/fundTradeSystem/res/e6.jpg',
		'1',
		'1',
		'',
		'Filter:progid:DXImageTransform.Microsoft.Slide(slideStyle=swap,bands=15,enabled=0,Duration=0.99)',
		'0', '#999999', '5', 'Pointer', 'Pointer', '', '90', '0', '#FFFFFF')
SwapDiv('wme1', '', '主&nbsp&nbsp&nbsp&nbsp 页',
		'/fundTradeSystem/res/blank.gif', '/fundTradeSystem/res/blank.gif',
		'0', '0', '/fundTradeSystem/res/blank.gif',
		'/fundTradeSystem/res/blank.gif', '0', '0', '30', '170', 'Helvetica',
		'Helvetica', '14pt', '14pt', 'normal', 'normal', '#000000', '#FFFFFF',
		'bold', 'bold', 'none', 'underline', 'transparent', 'transparent',
		'/fundTradeSystem/res/blank.gif', '/fundTradeSystem/res/blank.gif',
		'0', '0', '0', '0', '1px Dashed #BECEB9', '1px Dashed #BECEB9',
		'1px Dashed #BECEB9', '1px Dashed #BECEB9', '1px Dashed #000000',
		'1px Dashed #000000', '1px Dashed #000000', '1px Dashed #000000',
		'middle', 'center', '/fundTradeSystem/welcome.jsp', '', '',
		'contentFrame', '', '', '0', '/fundTradeSystem/res/blank.gif',
		'/fundTradeSystem/res/blank.gif', 'auto', 'auto', '0', '0', '0')
SwapDiv('wme2', 'wme1', '基 金 管 理', _, _, _, _,
		'/fundTradeSystem/res/arrow.gif',
		'/fundTradeSystem/res/arrowwhitetiny.gif', '7', '7', _, _,
		'Times New Roman,Times,serif', _, _, _, _, _, _, _, _, _, _, _, _, _,
		_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, '', _, _, _, _, _, '0',
		_, _, _, _, _, _, _)
FreeLayer(
		'wme4',
		'',
		'5',
		'v',
		'10',
		'0',
		'2',
		'2',
		'1px Solid #999999',
		'1px Solid #999999',
		'1px Solid #999999',
		'1px Solid #999999',
		'transparent',
		'/fundTradeSystem/res/e6.jpg',
		'1',
		'1',
		'',
		'Filter:progid:DXImageTransform.Microsoft.Checkerboard(squa/fundTradeSystem/resX=16,squa/fundTradeSystem/resY=16,direction=up,enabled=0,Duration=0.3) progid:DXImageTransform.Microsoft.RandomDissolve(,enabled=0,Duration=0.3)',
		'1', '#999999', '5', '90')
SwapDiv('wme3', 'wme1', '添加基金产品', _, _, _, _, _, _, _, _, 'auto', 'auto', _, _,
		'10pt', '10pt', _, _, _, _, 'normal', _, _, _, _, _, _, _, _, _, _, _,
		_, _, _, _, _, _, _, _, _, _, '/fundTradeSystem//fundMgr?act=input', _,
		_, 'contentFrame', _, _, '0', _, _, _, _, _, _, _)
SwapDiv('wme5', 'wme3', '查询基金产品', _, _, _, _, _, _, _, _, _, _, _, _, _, _, _,
		_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _,
		_, '/fundTradeSystem/fundMgr?act=loadPagedFunds', _, _, 'contentFrame',
		_, _, '0', _, _, _, _, _, _, _)
InitDiv();
SwapDiv('wme8', 'wme2', '客户资料管理', _, _, _, _, _,
		'/fundTradeSystem/res/arrow.gif', _, _, _, _, 'Helvetica', _, _, _, _,
		_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _,
		_, _, _, _, _, _, _, '0', _, _, _, _, _, _, _)
FreeLayer('wme21', 'wme4', _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _,
		_, _, _)
SwapDiv('wme20', 'wme3', '添加新客户', _, _, _, _, _, _, _, _, _, _, _, _, _, _, _,
		_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _,
		_, '/fundTradeSystem/clientMgr?act=input', _, _, 'contentFrame', _, _,
		'0', _, _, _, _, _, _, _)
SwapDiv('wme22', 'wme20', '查询客户基本信息', _, _, _, _, _, _, _, _, _, _, _, _, _, _,
		_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _,
		_, _, '/fundTradeSystem/clientMgr?act=loadPagedClients', _, _,
		'contentFrame', _, _, '0', _, _, _, _, _, _, _)
SwapDiv('wme23', 'wme20', '查询客户详细信息', _, _, _, _, _, _, _, _, _, _, _, _, _, _,
		_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _,
		_, _, '/fundTradeSystem/clientMgr?act=loadPagedClientsDetail', _, _,
		'contentFrame', _, _, '0', _, _, _, _, _, _, _)
InitDiv();
SwapDiv('wme9', 'wme2', '客户资金账户管理', _, _, _, _, _, _, _, _, _, _, 'Helvetica',
		_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _,
		_, _, _, _, _, _, _, _, _, _, _, '0', _, _, _, _, _, _, _)
FreeLayer('wme10', 'wme4', _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _,
		_, _, _)
SwapDiv('wme11', 'wme3', '资金账户开户', _, _, _, _, _, _, _, _, _, _, _, _, _, _, _,
		_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _,
		_, '/fundTradeSystem/financial_accountMgr?act=input', _, _,
		'contentFrame', _, _, '0', _, _, _, _, _, _, _)
SwapDiv('wme12', 'wme3', '查询资金账户', _, _, _, _, _, _, _, _, _, _, _, _, _, _, _,
		_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _,
		_,
		'/fundTradeSystem/financial_accountMgr?act=loadPagedFinancialAccounts',
		_, _, 'contentFrame', _, _, '0', _, _, _, _, _, _, _)
SwapDiv('wme13', 'wme3', '追加资金账户', _, _, _, _, _, _, _, _, _, _, _, _, _, _, _,
		_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _,
		_, '/fundTradeSystem/financial_accountMgr?act=forAdd', _, _,
		'contentFrame', _, _, '0', _, _, _, _, _, _, _)
SwapDiv('wme14', 'wme3', '取出账户资金', _, _, _, _, _, _, _, _, _, _, _, _, _, _, _,
		_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _,
		_, '/fundTradeSystem/financial_accountMgr?act=forCut', _, _,
		'contentFrame', _, _, '0', _, _, _, _, _, _, _)
SwapDiv(
		'wme24',
		'wme20',
		'冻结和解冻账户资金',
		_,
		_,
		_,
		_,
		_,
		_,
		_,
		_,
		_,
		_,
		_,
		_,
		_,
		_,
		_,
		_,
		_,
		_,
		_,
		_,
		_,
		'none',
		_,
		_,
		_,
		_,
		_,
		_,
		_,
		_,
		_,
		_,
		_,
		_,
		_,
		_,
		_,
		_,
		_,
		_,
		'/fundTradeSystem/financial_accountMgr?act=loadPagedFundAccountsStatus',
		_, _, 'contentFrame', _, _, '0', _, _, _, _, _, _, _)
SwapDiv('wme25', 'wme20', '资金进出记录', _, _, _, _, _, _, _, _, _, _, _, _, _, _,
		_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _,
		_, _, '/fundTradeSystem/acctransinfoMgr?act=loadPagedAccountTransInfo',
		_, _, 'contentFrame', _, _, '0', _, _, _, _, _, _, _)
InitDiv();
SwapDiv('wme15', 'wme9', '基金交易管理', _, _, _, _, _, _, _, _, _, _, _, _, _, _, _,
		_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _,
		_, _, _, _, _, _, _, '0', _, _, _, _, _, _, _)
FreeLayer('wme16', 'wme4', _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _,
		_, _, _)
SwapDiv('wme17', 'wme3', '购买基金', _, _, _, _, _, _, _, _, _, _, _, _, _, _, _,
		_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _,
		_, '/fundTradeSystem/fund_tradeMgr?act=buyFund', _, _, 'contentFrame',
		_, _, '0', _, _, _, _, _, _, _)
SwapDiv('wme18', 'wme3', '基金账号查询', _, _, _, _, _, _, _, _, _, _, _, _, _, _, _,
		_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _,
		_, '/fundTradeSystem/fund_tradeMgr?act=loadPagedFundAccountInfo', _, _,
		'contentFrame', _, _, '0', _, _, _, _, _, _, _)
SwapDiv('wme19', 'wme3', '基金赎回', _, _, _, _, _, _, _, _, _, _, _, _, _, _, _,
		_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _,
		_, '/fundTradeSystem/fund_tradeMgr?act=saleFund', _, _, 'contentFrame',
		_, _, '0', _, _, _, _, _, _, _)
SwapDiv('wme26', 'wme20', '交易记录', _, _, _, _, _, _, _, _, _, _, _, _, _, _, _,
		_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _,
		_, '/fundTradeSystem/fund_tradeMgr?act=loadPagedTradeRecord', _, _,
		'contentFrame', _, _, '0', _, _, _, _, _, _, _)
SwapDiv('wme27', 'wme20', '持仓情况', _, _, _, _, _, _, _, _, _, _, _, _, _, _, _,
		_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _,
		_, '/fundTradeSystem/fundholdinginfoMgr?act=loadPagedFundHolding', _,
		_, 'contentFrame', _, _, '0', _, _, _, _, _, _, _)
InitDiv();
HideDiv();